### PR TITLE
Monocular is no more

### PR DESCRIPTION
**Pull request by vfarcic**

### CODE REVIEW

**Comment by haysclark** [comment]
@vfarcic Could you include a bit more context of why "Monocular is no more". Is the project being sunset, etc.  -Thanks

**Comment by helmuthva** [comment]
@vfarcic `jx install ...` fails because of this - is there a workaround?

**Comment by vfarcic** [comment]
@rawlingsj ^^^

**Comment by Cressida8** [comment]
jx install fails now.. how to proceed?

**Comment by chaoyangnz** [comment]
!!!

**Comment by helmuthva** [comment]
Has been fixed with https://github.com/jenkins-x/jenkins-x-platform/commit/46d3da2232b4ce7956834058eb1780abc9befc3f, `jx install` working again.

**Pull request merged**
