### PR TITLE
Update README.md to fix images are not displayed

### PR DESCRIPTION
**Pull request by shenxianpeng**
Current README.md page images are not displayed, not pretty for a project as big as Jenkins.

### CODE REVIEW

**Comment by shenxianpeng** [comment]
fix Jenkin X README md
now, it works on my fork repo.

**Comment by ccojocar** [comment]
@shenxianpeng Please could you rebase and fix the conflicts? Thanks!

**Comment by shenxianpeng** [comment]
@ccojocar This issue had been fixed, so can I just close this PR? Thanks!

**Comment by shenxianpeng** [comment]
Closed without reply.

**Pull request closed without merging**
