### PR TITLE
fix: Remove workflow controller as unused

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by ccojocar** [comment]
@rawlingsj Please can you rebase and fix the conflicts? Thanks!

**Comment by mrageh** [comment]
@rawlingsj I've created a PR to remove the deprecated [`jx controller workflow`](https://github.com/jenkins-x/jx/pull/6906) from the main `jx` binary. But I think this may need to be merged first. 

Any chance we could merge this PR in the near future?

**Comment by mrageh** [comment]
We should close this in favour off #7048

**Pull request closed without merging**
