### PR TITLE
fix: use a docker image with jx + helm + kubectl for gc previews

### PR DESCRIPTION
**Pull request by jstrachan**
fixes https://github.com/jenkins-x/jx/issues/2723

### CODE REVIEW

**Comment by rawlingsj** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **jstrachan**

If they are not already assigned, you can assign the PR to them by writing `/assign @jstrachan` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/jenkins-x/jenkins-x-platform/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by vbehar** [comment]
fixes https://github.com/jenkins-x/jx/issues/2723

**Comment by vbehar** [comment]
@jstrachan can you please approve this one ? thanks

**Pull request merged**
