### PR TITLE
MavenSettingsSecurityXML added to templates and values file

### PR DESCRIPTION
**Pull request by almerico**
fixes https://github.com/jenkins-x/jenkins-x-platform/issues/3413

### CODE REVIEW

**Comment by almerico** [comment]
@ccojocar is it possible can you please take a look without this property we can't automate cluster upgrade in activiti

**Comment by salaboy** [comment]
This is really important for us and for everyone using settings-security.xml.. which I will assume that everyone will use in a way or another. @jstrachan @ccojocar thanks for your feedback.. if we can improve this in any way let us know

**Pull request merged**
