### PR TITLE
[wip] fix: update chart versions for prelim  k8s 1.16 support

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

### CODE REVIEW

**Comment by ankitm123** [comment]
Removing also jenkins support from the charts repo, since it's deprecated anyways (it was trying to install jenkins master). I think the chart versions in this PR are not available in the jenkins helm repo, and need to be added.

**Comment by ankitm123** [comment]
What is the error message?

**Comment by hferentschik** [comment]
@ankitm123 

```
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "monocular" chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "**" chart repository
Update Complete.
Error: Can't get a valid version for repositories chartmuseum. Try changing the version constraint in requirements.yaml
make: *** [build] Error 1
```

**Comment by hferentschik** [comment]
@ankitm123, I am wondering how this is moving forward towards supporting k8s 1.16. I think there will be much more needed to get there, in particular, we will need to make changes in `jx` and its dependencies as well. It is super important to move us forward, but personally I would prefer if we can take this a bit slower.

There are two big changes panned for `jx`, one to move to go 1.13 which is not directly related to a k8s update, but we are hoping it helps with the bigger challenge of upgrading the dependencies in `jx` to a later k8s version. The latter is quite a challenge and we have had several attempts to do so, but have not yet succeeded. The hope is moving to go 1.13 helps a little bit since there were several improvements in go mod between 1.12 and 1.13.

**Comment by hferentschik** [comment]
Here is a now out of data pull request trying a dependency upgrade on `jx` - https://github.com/jenkins-x/jx/pull/6413/. I would feel much better about trying to get into everything else needed for a K8s upgrade once we sorted these dependency issues.

**Comment by hferentschik** [comment]
@ankitm123, regarding this pull request, what is the net effect here and is this backward compatible? If this is just upgrading some Chart versions and there is no compatibility issue there would be no reason to upgrade versions.

**Comment by ankitm123** [comment]
> @ankitm123, I am wondering how this is moving forward towards supporting k8s 1.16. I think there will be much more needed to get there, in particular, we will need to make changes in `jx` and its dependencies as well. It is super important to move us forward, but personally I would prefer if we can take this a bit slower.

This is just one of the many things that needs to be done to get to K8s 1.16+. I upgraded the versions of the chart to the versions which support the changes introduced in 1.16 (removing v1beta1 apiVersion). https://github.com/jenkins-x/jx/issues/6957    



> Here is a now out of data pull request trying a dependency upgrade on `jx` - [jenkins-x/jx#6413](https://github.com/jenkins-x/jx/pull/6413). I would feel much better about trying to get into everything else needed for a K8s upgrade once we sorted these dependency issues.

This is nice, I will take a look over the weekend. 

> @ankitm123, regarding this pull request, what is the net effect here and is this backward compatible? If this is just upgrading some Chart versions and there is no compatibility issue there would be no reason to upgrade versions.

I talked to @deanesmith on slack abt compatibility issues with upgrading. For now, do u suggest something along the lines of jx labs to work on this, and once we have a good understanding of what will break, and what changes need to be done, it can be brought more mainstream. wdyt?

**Comment by deanesmith** [comment]
Suggestion is to convene 2 weeks to establish an approach and a schedule.  At that time there will be some capacity to support an effort where a CloudBees engineer can be involved to an extent.  Thank you for keeping on this @ankitm123 !

**Comment by alexvolsh** [comment]
@ankitm123 @MarckK @hferentschik @deanesmith 
Hi! I've already upgraded charts for docker-registry and chartmuseum with k8s 1.16 support in the stable repo.
@ankitm123 you can change docker-registry and chartmuseum for the following versions:
```
- condition: chartmuseum.enabled
  name: chartmuseum
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 2.12.1
- condition: docker-registry.enabled
  name: docker-registry
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.9.3
```

**Comment by abayer** [comment]
The error, fyi:

```
helm lint jenkins-x-platform
==> Linting jenkins-x-platform
[ERROR] templates/: render error in "jenkins-x-platform/templates/jenkins-x-pod-templates.yaml": template: jenkins-x-platform/templates/jenkins-x-pod-templates.yaml:63:14: executing "jenkins-x-platform/templates/jenkins-x-pod-templates.yaml" at <.Values.jenkins.Agent.Enabled>: nil pointer evaluating interface {}.Agent
Error: 1 chart(s) linted, 1 chart(s) failed
make: *** [build] Error 1
```

I think I'm going to go ahead with #7171 on its own and then this can be repurposed to just deal with removing the deprecated stuff.

**Comment by ankitm123** [comment]
Right, the issue is that I tried to remove jenkins chart, I will not remove it in this PR, I see some code in jx trying to access it, probably another PR would make sense. Also I think you should change the version of docker registry in #7171 (unless it's already done, and I missed it) :)

**Comment by ankitm123** [comment]
closing this in favor of #7171, will open another PR to take care of the deprecated stuff

**Pull request closed without merging**
