### PR TITLE
chore(docs): Updated README.md

### PR DESCRIPTION
**Pull request by sumitkharche**
- Added license section
- Added missing punctuation

### CODE REVIEW

**Comment by sumitkharche** [comment]
@ccojocar Can you please review this PR.

**Comment by sumitkharche** [comment]
@ccojocar Thanks for the quick review. 
Is this PR considered for hacktoberfest?

**Comment by ccojocar** [comment]
@sumitkharche The commit messages should follow to semantic pull request. The guidelines are here https://www.conventionalcommits.org/en/v1.0.0/. Essentially, you need to add something like `doc: ` as prefix in front of every commit message. Please can you fix your commits? Thanks

**Comment by ccojocar** [comment]
I am no sure about Hacktoberfest. @MarckK could provide more details. Thanks!

**Pull request merged**
